/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import control.Coneccion;
import control.ControlEventos;
import java.util.ArrayList;
import java.util.List;
import modelo.Localidad;

/**
 *
 * @author PC
 */
public class DialogInfoEvento extends javax.swing.JDialog {
    ControlEventos ce = new ControlEventos();
    String equipos;
    String[] infoEvento;
    int idCliente,idEvento;
    List<Localidad> listaLocalidades= new ArrayList<>();
    /**
     * Creates new form DialogInfoEvento
     */
    public DialogInfoEvento(java.awt.Frame parent, boolean modal, int idEvento,int idCliente) {
        super(parent, modal);
        initComponents();
        this.idEvento=idEvento;
        setDataInfo();
        this.idCliente=idCliente;
    }
//    public DialogInfoEvento(String equipo1, String equipo2, int idCliente){
//        initComponents();
//        this.equipo1=equipo1;
//        this.equipo2=equipo2;
//        setDataInfo();
//        this.idCliente=idCliente;
//    }
    private void setDataInfo(){
        infoEvento=ce.infoEvento(new Coneccion(), idEvento);
        if(infoEvento!=null){
            lugartxt.setText(infoEvento[1]);
            fechatxt.setText(infoEvento[4]);
            horatxt.setText(infoEvento[5]);
            equipos=infoEvento[6];
        }
        
    listaLocalidades =ce.infoLocalidad(new Coneccion(),Integer.parseInt(infoEvento[0]));    
        if(listaLocalidades!=null){
            double precio1 = listaLocalidades.get(0).getPrecio();
            String price1 = String.valueOf(precio1);
            precioGeneralN.setText(price1);
            double precio2 = listaLocalidades.get(1).getPrecio();
            String price2 = String.valueOf(precio2);
            precioGeneralS.setText(price2);
            double precio3 = listaLocalidades.get(2).getPrecio();
            String price3 = String.valueOf(precio3);
            precioTribuna.setText(price3);
            double precio4 = listaLocalidades.get(3).getPrecio();
            String price4 = String.valueOf(precio4);
            precioPalco.setText(price4);
        }
   
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        precioPalco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        precioTribuna = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precioGeneralN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        precioGeneralS = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lugartxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fechatxt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        horatxt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        palcoB = new javax.swing.JToggleButton();
        surB = new javax.swing.JToggleButton();
        norteB = new javax.swing.JToggleButton();
        tribunaB = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        atrasB = new javax.swing.JButton();
        siguienteB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del evento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14)), javax.swing.BorderFactory.createEtchedBorder())); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Precio por categoría(USD)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)))); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Precio Palco:  ");
        jPanel6.add(jLabel1);

        precioPalco.setText("p1");
        jPanel6.add(precioPalco);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Precio Tribuna:");
        jPanel6.add(jLabel2);

        precioTribuna.setText("p2");
        jPanel6.add(precioTribuna);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Precio General Norte:");
        jPanel6.add(jLabel3);

        precioGeneralN.setText("p3");
        jPanel6.add(precioGeneralN);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Precio General Sur:");
        jPanel6.add(jLabel4);

        precioGeneralS.setText("p4");
        jPanel6.add(precioGeneralS);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(6, 1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Lugar del evento:");
        jPanel7.add(jLabel7);

        lugartxt.setText("evt");
        jPanel7.add(lugartxt);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Fecha del evento:");
        jPanel7.add(jLabel9);

        fechatxt.setText("fec");
        jPanel7.add(fechatxt);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Hora del evento:");
        jPanel7.add(jLabel11);

        horatxt.setText("hour");
        jPanel7.add(horatxt);

        jPanel3.add(jPanel7);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(palcoB);
        palcoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/palcoLoc.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(palcoB, gridBagConstraints);

        buttonGroup1.add(surB);
        surB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/surLoc.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 3);
        jPanel4.add(surB, gridBagConstraints);

        buttonGroup1.add(norteB);
        norteB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/norteLoc.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 9);
        jPanel4.add(norteB, gridBagConstraints);

        buttonGroup1.add(tribunaB);
        tribunaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/generalLoc.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(tribunaB, gridBagConstraints);

        jPanel2.add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(136, 35));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 50));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        atrasB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/returnicon.png"))); // NOI18N
        atrasB.setText("Atrás");
        atrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 3, 17, 3);
        jPanel5.add(atrasB, gridBagConstraints);

        siguienteB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agreeicon.png"))); // NOI18N
        siguienteB.setText("Siguiente");
        siguienteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 3, 17, 3);
        jPanel5.add(siguienteB, gridBagConstraints);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBActionPerformed
        dispose();
    }//GEN-LAST:event_atrasBActionPerformed

    private void siguienteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBActionPerformed
        listaLocalidades =ce.infoLocalidad(new Coneccion(),Integer.parseInt(infoEvento[0]));
        if(norteB.isSelected()){
            //new GeneralN2(listaLocalidades.get(0).getNumeroAsientos()).setVisible(true);
            new GeneralN2Dialog(null,true,listaLocalidades.get(0).getNumeroAsientos(),listaLocalidades.get(0).getIdLocalidad(), listaLocalidades.get(0).getPrecio(), idCliente,equipos).setVisible(true);
        
        }
        if(surB.isSelected()){
            //new GeneralS2(listaLocalidades.get(1).getNumeroAsientos()).setVisible(true);
            new GeneralS2Dialog(null,true,listaLocalidades.get(1).getNumeroAsientos(),listaLocalidades.get(1).getIdLocalidad(), listaLocalidades.get(1).getPrecio(), idCliente,equipos).setVisible(true);
        }
        if(tribunaB.isSelected()){
            //new Tribuna2(listaLocalidades.get(2).getNumeroAsientos(),listaLocalidades.get(2).getIdLocalidad(), listaLocalidades.get(2).getPrecio(), idCliente).setVisible(true);
            new Tribuna2Dialog(null,true,listaLocalidades.get(2).getNumeroAsientos(),listaLocalidades.get(2).getIdLocalidad(), listaLocalidades.get(2).getPrecio(), idCliente, equipos).setVisible(true);
            
        }
        if(palcoB.isSelected()){
            //new Palco2(listaLocalidades.get(3).getNumeroAsientos()).setVisible(true);
            new Palco2Dialog(null, true,listaLocalidades.get(3).getNumeroAsientos(), listaLocalidades.get(3).getIdLocalidad(), listaLocalidades.get(3).getPrecio(),idCliente,equipos ).setVisible(true);
        }
    }//GEN-LAST:event_siguienteBActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fechatxt;
    private javax.swing.JLabel horatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lugartxt;
    private javax.swing.JToggleButton norteB;
    private javax.swing.JToggleButton palcoB;
    private javax.swing.JLabel precioGeneralN;
    private javax.swing.JLabel precioGeneralS;
    private javax.swing.JLabel precioPalco;
    private javax.swing.JLabel precioTribuna;
    private javax.swing.JButton siguienteB;
    private javax.swing.JToggleButton surB;
    private javax.swing.JToggleButton tribunaB;
    // End of variables declaration//GEN-END:variables
}
