/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class DialogInformacionCompra extends javax.swing.JDialog {
    double preciou;
    int cant;
    String equipos;
    /**
     * Creates new form DialogInformacionCompra
     */
    public DialogInformacionCompra(java.awt.Frame parent, boolean modal,int numBoletos, double precio,String equipos) {
        super(parent, modal);
        initComponents();
        this.equipos=equipos;
        this.cant=numBoletos;
        asientostxt.setText(Integer.toString(numBoletos));
        totaltxt.setText(Double.toString(precio*numBoletos));
        this.preciou=precio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        asientostxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de la localidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("MS UI Gothic", 1, 14)), javax.swing.BorderFactory.createEtchedBorder())); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Número de boletos a adquirir:");
        jPanel2.add(jLabel1);

        asientostxt.setText("asientos");
        jPanel2.add(asientostxt);

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Precio a pagar(No incluye IVA):");
        jPanel2.add(jLabel3);

        totaltxt.setText("total");
        jPanel2.add(totaltxt);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CANCELPNG.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rebuyres.png"))); // NOI18N
        jButton2.setText("Comprar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Tu compra se ha realizado con éxito.");
        dispose();
        //new Factura(subt).setVisible(true);
        new FacturaDialog(null,true,preciou, cant,equipos).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asientostxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel totaltxt;
    // End of variables declaration//GEN-END:variables
}
