/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import control.Coneccion;
import control.ControlEventos;
import control.ControlPersonas;
import java.awt.Component;
import java.util.List;
import javax.swing.JButton;
import modelo.Evento;
/**
 *
 * @author PC
 */
public class VentanaEventos extends javax.swing.JFrame {
   String usuario,pass,equipo1,equipo2,equipos;
   Coneccion con;
   ControlEventos ce = new ControlEventos();
   ControlPersonas cp= new ControlPersonas();
   String[] clientData;
   List <Evento> lista;
    /**
     * Creates new form VentanaEventos
     */
    public VentanaEventos(String usuario, String pass,Coneccion con) {
       initComponents();
       this.pass=pass;
       this.usuario=usuario;
       this.con=con;
       clientData= cp.buscarCliente(con, usuario, pass);
       setBotones();
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        evB1 = new javax.swing.JButton();
        evB2 = new javax.swing.JButton();
        evB3 = new javax.swing.JButton();
        evB4 = new javax.swing.JButton();
        evB5 = new javax.swing.JButton();
        evB6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(436, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "EVENTOS DISPONIBLES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18)), javax.swing.BorderFactory.createEtchedBorder())); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jPanel2.setPreferredSize(new java.awt.Dimension(420, 25));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        evB1.setText("jButton4");
        evB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 18, 11);
        jPanel2.add(evB1, gridBagConstraints);

        evB2.setText("jButton5");
        evB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evB2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 18, 11);
        jPanel2.add(evB2, gridBagConstraints);

        evB3.setText("jButton1");
        evB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evB3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 18, 11);
        jPanel2.add(evB3, gridBagConstraints);

        evB4.setText("jButton2");
        evB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evB4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 18, 11);
        jPanel2.add(evB4, gridBagConstraints);

        evB5.setText("jButton3");
        evB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evB5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 18, 11);
        jPanel2.add(evB5, gridBagConstraints);

        evB6.setText("jButton6");
        evB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evB6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 18, 11);
        jPanel2.add(evB6, gridBagConstraints);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modifyUserIcon.png"))); // NOI18N
        jButton7.setText("Modificar Cuenta");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 15, 12);
        jPanel2.add(jButton7, gridBagConstraints);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticketIcon.png"))); // NOI18N
        jButton9.setText("Otros Eventos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 15, 12);
        jPanel2.add(jButton9, gridBagConstraints);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ssCancelIcon.png"))); // NOI18N
        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 15, 12);
        jPanel2.add(jButton8, gridBagConstraints);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //new DialogModificarUsuario(this,true,usuario, pass,con).setVisible(true);
        new DialogCrearModificar(this, true,false, true, usuario, pass, con).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       new DialogOtrosEventos(this,true,clientData).setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void evB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evB1ActionPerformed
       //new InformacionEvento(equipo1, equipo2, Integer.parseInt(clientData[11])).setVisible(true);
        new DialogInfoEvento(this, true,lista.get(0).getIdEvento(), Integer.parseInt(clientData[11])).setVisible(true);
    }//GEN-LAST:event_evB1ActionPerformed

    private void evB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evB2ActionPerformed

        new DialogInfoEvento(this, true,lista.get(1).getIdEvento(), Integer.parseInt(clientData[11])).setVisible(true);
    }//GEN-LAST:event_evB2ActionPerformed

    private void evB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evB3ActionPerformed

        new DialogInfoEvento(this, true,lista.get(2).getIdEvento(), Integer.parseInt(clientData[11])).setVisible(true);
    }//GEN-LAST:event_evB3ActionPerformed

    private void evB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evB4ActionPerformed

        new DialogInfoEvento(this, true,lista.get(3).getIdEvento(), Integer.parseInt(clientData[11])).setVisible(true);
    }//GEN-LAST:event_evB4ActionPerformed

    private void evB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evB5ActionPerformed

        new DialogInfoEvento(this, true,lista.get(4).getIdEvento(), Integer.parseInt(clientData[11])).setVisible(true);
    }//GEN-LAST:event_evB5ActionPerformed

    private void evB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evB6ActionPerformed

        new DialogInfoEvento(this, true,lista.get(5).getIdEvento(), Integer.parseInt(clientData[11])).setVisible(true);
    }//GEN-LAST:event_evB6ActionPerformed
    public void setBotones(){
        int j;
        Component[] buttons = jPanel2.getComponents();
        lista = ce.botonesEvento(new Coneccion());
        if((lista.size()-1) < (buttons.length-4)){
                for(j=0; j<lista.size(); j++){
                    JButton bt = (JButton) buttons[j];
                    bt.setText(lista.get(j).getEquipo1()+" vs "+lista.get(j).getEquipo2());
                }
                for(int k=buttons.length-4; k>=j;k--){
                    JButton bt = (JButton) buttons[k];
                    bt.setText("Proximamente...");
                    bt.setEnabled(false);
                }
            }else{
            for(int i=0; i<=buttons.length-4; i++){
                 JButton bt = (JButton) buttons[i];
                 bt.setText(lista.get(i).getEquipo1()+" vs "+lista.get(i).getEquipo2());
                }
        }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton evB1;
    private javax.swing.JButton evB2;
    private javax.swing.JButton evB3;
    private javax.swing.JButton evB4;
    private javax.swing.JButton evB5;
    private javax.swing.JButton evB6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
